databases:
  - name: micronus
    databaseName: micronus
    user: micronus_user

services:
  - type: web
    name: rendertest
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micronus
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false